stoerung: str = "for $x in //StopEvent[descendant::EstimatedTime]/descendant::*[local-name(.)='SituationNumber'] return //PtSituation[*[local-name(.)='SituationNumber'] = $x]/*[local-name(.)='Description']"
lon: str = "//GeoPosition/Longitude/text()"
lat: str = "//GeoPosition/Latitude/text()"
lons: str = "//TripResult[1][descendant::Service[count(ServiceSection) = 1][ServiceSection/Mode/PtMode = 'tram']]/descendant::Projection/Position/Longitude/text()"
lats: str = "//TripResult[1][descendant::Service[count(ServiceSection) = 1][ServiceSection/Mode/PtMode = 'tram']]/descendant::Projection/Position/Latitude/text()"
stations: str = "//TripResult[1]/descendant::TimedLeg/*/StopPointRef/replace(., '([a-z]*:[0-9]*:[0-9]*):.*', '$1')"
line_number: str = "//ServiceSection[*/PtMode='tram']/PublishedLineName/Text/text()"
line_string: str = "//ServiceSection[*/PtMode='tram']/normalize-space(RouteDescription/Text)"
line_trias_id: str = "//ServiceSection[*/PtMode='tram']/LineRef/text()"
line_start: str = "//ServiceSection[*/PtMode='tram']/../OriginStopPointRef/replace(., '([a-z]*:[0-9]*:[0-9]*):.*', '$1')"
line_end: str = "//ServiceSection[*/PtMode='tram']/../DestinationStopPointRef/replace(., '([a-z]*:[0-9]*:[0-9]*):.*', '$1')"
